### ISSUE TITLE
Sonobuoy shows failed tests as success

### ISSUE THREAD

**Issue by gogineni99** [vmware-tanzu/sonobuoy#1025]
[TEST-Alertmanager_-_Alertmanager_statefuleset_executeK8sTests.xml.log](https://github.com/vmware-tanzu/sonobuoy/files/3918108/TEST-Alertmanager_-_Alertmanager_statefuleset_executeK8sTests.xml.log)
[sonobuoy_results.yaml.log](https://github.com/vmware-tanzu/sonobuoy/files/3918109/sonobuoy_results.yaml.log)

**What steps did you take and what happened:**
Created a custom plugin to run tests. Created a junit result format. Please see attached file of the output junit xml. The test actually failed. But Sonobuoy report it as success in 'sonobuoy results' as well as in the retrieved tar yaml file (attached)

**What did you expect to happen:**
Failures in junit xml should be seen as errors in results output file as well as console output

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.16.4
- Kubernetes version: (use `kubectl version`):v1.16.3
- Kubernetes installer & version:v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
I'm going to tinker on this for a few min to see what's going on.

My first thought (looking at just the files uploaded) was that the files have the `.log` suffix. However, looking at the sonobuoy_results file, I can see that the file was parsed (and didnt have the .log suffix so maybe that was added later?) but that also the suite was parsed and showed the one test.

So the file did get parsed but the failure did not get reported for some reason. Will respond after I try and repro/debug this.

If you have additional logs from the run that would be helpful; ideally the whole tarball if possible.

**Comment by johnSchnake** [comment]
So the issue is that the logic is looking specifically for the `<failure >` sub-item in the testcase but in yours there is only an `<error ...>`. 

I will lookup the junit spec and see if I can find any sort of clear guidance. If errors can be reported this way without marking a failure than we should be considering that field as well.

What tool/framework/etc did you use to generate the JUnit? It will help me describe/document the issue and test cases this may introduce.

**Comment by johnSchnake** [comment]
From what I can see the error and failure cases in xunit are intentionally distinct so it isnt a situation where the output should include both.

The junit types we have do not currently have an error field but adding one won't be hard and should be identical otherwise to the failure type.

If someone has a real source of truth for the junit xsd let me know; I have found inklings of them is all. E.g. https://gist.github.com/erikd/4192748 and https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd

**Comment by gogineni99** [comment]
The .log was appended to file later just to upload. I was using a custom code to generate these XML files. I can modify my code to record these in failure field.

But from my understanding - "Failures notify of an invalid test result, errors indicate an unexpected test execution."

However, It would be good to consider both failure and error fields
