### ISSUE TITLE
Minikube conformance tests inconclusive

### ISSUE THREAD

**Issue by sebgoa** [vmware-tanzu/sonobuoy#1036]
**What steps did you take and what happened:**

I followed the README step by step against a minikube endpoint

```
$ sonobuoy run --wait
INFO[0000] created object                                name=sonobuoy namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=sonobuoy resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount-sonobuoy namespace= resource=clusterrolebindings
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm namespace=sonobuoy resource=configmaps
INFO[0000] created object                                name=sonobuoy namespace=sonobuoy resource=pods
INFO[0000] created object                                name=sonobuoy-master namespace=sonobuoy resource=services
$ results=$(sonobuoy retrieve)
$ echo $results
201912082157_sonobuoy_cd42ca45-5448-4cae-a0a1-37094803c9de.tar.gz
$ sonobuoy results $results
Plugin: e2e
Status: unknown
Total: 0
Passed: 0
Failed: 0
Skipped: 0

Plugin: systemd-logs
Status: passed
Total: 1
Passed: 1
Failed: 0
Skipped: 0

```

**What did you expect to happen:**

I expected to see the results of a lot of e2e tests run against my minikube endpoint. The stdout I get implies that nothing was run against minikube except one `systemd-logs` test.

**Anything else you would like to add:**
no

**Environment:**

- Sonobuoy version: 
```
$ sonobuoy version
Sonobuoy Version: v0.16.5
MinimumKubeVersion: 1.14.0
MaximumKubeVersion: 1.16.99
GitSHA: 99d45a1492050fcb58585568aeeae9c3e4a392ba
API Version check skipped due to missing `--kubeconfig` or other error
```

- Kubernetes version: (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version:

```
$ minikube version
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad
```

**Comment by zubron** [comment]
Hi @sebgoa. Sorry that you're having issues running the end-to-end tests. Given that the systemd-logs test ran successfully, it seems like everything is configured for Sonobuoy to run. Without seeing the logs or the results file, it's difficult to say what went wrong when trying to run the e2e tests. Is there any chance you could share the results tarball with us so we can take a look?

**Comment by johnSchnake** [comment]
So as of Kubernetes 1.14.0 the conformance test image was running the tests via a bash script which had a particularly nasty issue that keeps rearing its head. It causes the plugin to exit early and not report results at all which is, my guess, what you hit.

xref https://github.com/kubernetes/kubernetes/issues/83272

The proof would be if you open up the tarball and look in the podlogs for the plugin. If you see 

```
/run_e2e.sh: line 65: wait: `6
15': not a pid or valid job spec
```

Sometimes you also see no pids instead of 2 like this:
```
/run_e2e.sh: line 65: wait: `': not a pid or valid job spec
```

**Comment by zubron** [comment]
@johnSchnake I initially thought it could be the bash script issue, but wouldn't this version combination result in the gorunner for the e2e tests being used? (sonobuoy 0.16.5, k8s 1.16.2)

**Comment by johnSchnake** [comment]
Doh! Thanks for pointing out that I misread. I accidentally read the "minimum k8s version" that sonobuoy would support as the k8s version.  You're absolutely right.

To debug further we'd need the tarball; @zubron is right that the golang-based runner should be used and that the pid issue wouldn't be raised if using the default option.

**Comment by sebgoa** [comment]
I moved the tarball to:

https://www.dropbox.com/s/y5ep381fzy72t23/201912082157_sonobuoy_cd42ca45-5448-4cae-a0a1-37094803c9de.tar.gz?dl=0

**Comment by johnSchnake** [comment]
So I will peek a bit more to see if I can find anything else, but this much is clear:

For some reason the `ginkgo` command (which is what actually runs the tests inside the test container) exited with status 1 _without saving the junit output_. I'll take a look at the upstream code and see how tests can start running but potentially avoid dumping the junit output.

But since there is no junit output, Sonobuoy can't inspect the result.

**Comment by johnSchnake** [comment]
I can't find any particular code path upstream that this must have followed; the lack of unique output is frustrating.

Sometimes you can see some output about exiting the tests or something like that; but nothing like that exists. But it is clear the the framework isn't even recounting the # of passed/failed tests so it isn't hitting the normal 'end of test suite' logic which would trigger the junit output.

Going to make this into an upstream ticket and reference this ticket. The full logs dont have to stick around if you dont want it to.  The most important part is just the end really:

```
[sig-api-machinery] Garbage collector 
  should orphan pods created by rc if delete options say so [Conformance]
  /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:698
[BeforeEach] [sig-api-machinery] Garbage collector
  /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:151
STEP: Creating a kubernetes client
Dec  8 22:32:26.677: INFO: >>> kubeConfig: /tmp/kubeconfig-991463219
STEP: Building a namespace api object, basename gc
STEP: Waiting for a default service account to be provisioned in namespace
[It] should orphan pods created by rc if delete options say so [Conformance]
  /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:698
STEP: create the rc
STEP: delete the rc
STEP: wait for the rc to be deleted

Ginkgo ran 1 suite in 33m41.830419581s
Test Suite Failed
2019/12/08 22:32:36 Saving results at /tmp/results
2019/12/08 22:32:36 running command: exit status 1
```

Showing a few of the output lines like `Test Suite Failed` but none of the other typical summary info. We need to have some sort of output that indicates why we aborted the tests; not certain we can hook into that though since the normal code flow is getting interrupted somehow.

I dont see any memory pressure/etc on the nodes; I would probably just rerun and wouldn't expect the problem to occur again. Let me know if it is persistent though.

**Comment by sebgoa** [comment]
I tried it several times and no luck.
I Upgraded minikube to the latest version and no luck.
I also ran minikube vm in virtualbox or hyperkit and that did not change anything

**Comment by johnSchnake** [comment]
I am trying to reproduce this, but I feel pretty certain that it is just a minikube/resource issue and not really a code issue in Sonobuoy. I'm trying to repro to see if we could still capture anythign better along this code path though.

The tests are just getting terminated in the middle of the run so it doesn't save the junit output (without the junit output, Sonobuoy will report the results as unknown). I wish the upstream was able to log something about it, but it may not have even had the capability to.

I just used minikube to run `sonobuoy run --mode=quick` and things worked fine; trying a full run now.

**Comment by johnSchnake** [comment]
Duriung my run I was able to reproduce the same effect (tests stopping suddently, not reporting junit, etc).

Then I checked the cluster events and saw the clear answer:
```
$ kubectl get events
LAST SEEN   TYPE      REASON           OBJECT          MESSAGE
4m40s       Warning   SystemOOM        node/minikube   System OOM encountered, victim process: e2e.test, pid: 10085
```

So I think this confirms that the answer is that you're running OOM and the main offender (the e2e tests) are getting nuked which causes the symptoms you're seeing.

**Comment by sebgoa** [comment]
I know it is closed, but what is the minimum memory requirement to run e2e tests ?

**Comment by johnSchnake** [comment]
I dont know that I've seen clear minimum requirements, unfortunately; even if it was pinned down at some point it could change with any addition of certain tests and also would depend on how you run the tests (parallelism) or if you have other non-test workloads running.

From my experience it is more common for users to use KinD instead of Minikube and I think (but am not exactly sure) that it uses a different model. When I check my nodes it says each uses 32Gb (not possible) but I tell docker locally to use as much memory as it wants on my mac (16 Gb) machine.

I would simply try moving from 2 to 3 or 4 and see how it works for you.
