### ISSUE TITLE
Errors querying the API server while monitoring plugins should not error the run

### ISSUE THREAD

**Issue by dmitry-irtegov** [vmware-tanzu/sonobuoy#1043]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I run test suite with the command:
`sonobuoy run --plugin-env=e2e.E2E_USE_GO_RUNNER=true --plugin-env=e2e.E2E_EXTRA_ARGS="--allowed-not-ready-nodes=1"`

Sonobuoy reports the test results as failed, but there are no test results in the archive
[201912101700_sonobuoy_052565c6-f6d5-4018-a9ca-572626bb1e2d.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/3948640/201912101700_sonobuoy_052565c6-f6d5-4018-a9ca-572626bb1e2d.tar.gz)
```
$ sonobuoy e2e 201912101700_sonobuoy_052565c6-f6d5-4018-a9ca-572626bb1e2d.tar.gz
ERRO[0000] could not get tests from archive: failed to find results file "plugins/e2e/results/global/junit_01.xml" in archive
$ cat ct/plugins/e2e/sonobuoy_results.yaml
name: e2e
status: failed
items:
- name: 'pods is forbidden: User "system:serviceaccount:sonobuoy:sonobuoy-serviceaccount"
    cannot list resource "pods" in API group "" in the namespace "sonobuoy"'
  status: failed
  meta:
    file: errors/global/error.json
  details:
    error: 'pods is forbidden: User "system:serviceaccount:sonobuoy:sonobuoy-serviceaccount"
      cannot list resource "pods" in API group "" in the namespace "sonobuoy"'
$ kubectl auth can-i list pods --as system:serviceaccount:sonobuoy:sonobuoy-serviceaccount
yes
$ sonobuoy version --kubeconfig dvi-5231-ct-1575995653-admin-config.yaml 
Sonobuoy Version: v0.16.5
MinimumKubeVersion: 1.14.0
MaximumKubeVersion: 1.16.99
GitSHA: 99d45a1492050fcb58585568aeeae9c3e4a392ba
API Version:  v1.16.3
```

**What did you expect to happen:**
To be able to inspect and list the failures that have occurred.

**Anything else you would like to add:**
(found this after I submitted the issue):
`sonobuoy run` with default settings (no `--plugin-env=e2e.E2E_USE_GO_RUNNER=true` option) on the same cluster passes the test.

**Environment:**

- Sonobuoy version: v0.16.5
- Kubernetes version: (use `kubectl version`): v1.16.3
- Kubernetes installer & version: custom
- Cloud provider or hardware configuration: AWS t2.xlarge
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04
- Sonobuoy tarball (which contains * below) https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.16.5/sonobuoy_0.16.5_linux_amd64.tar.gz

**Comment by johnSchnake** [comment]
Hi @dmitry-irtegov , sorry you're running into problems.

A few things to note after just looking at this for a minute or two:
 - the error does seem surprising since you can open the tarball and see that we could get the podlogs for the e2e run and actually ran many tests. It clearly had permissions to do a great many things to get that far.
 - Slightly confused about the kubeconfig settings; in the issue description you specify kubeconfig when checking the version (`sonobuoy version --kubeconfig dvi-5231-ct-1575995653-admin-config.yaml`) but do not specify it when running the `kubectl auth can-i ...` command. I just want to make sure that you're being consistent using the same kubeconfig for running the tests as for checking the auth and such.
 - The error came from the aggregator itself failing to monitor the plugin; not the plugin reporting the error. You can tell that by the aggregator log line: `{"level":"info","msg":"received internal aggregator result","node":"global","plugin_name":"e2e","time":"2019-12-10T18:49:30Z"}` specifying it was an internal aggregator result.
 - It is also very strange that the queries didn't really run; again the aggregator itself seemed unable to query anything about the cluster. You can tell this by the fact that the `meta/config.json` shows you're querying lots of resources but there are no logs for querying those, no data from the results (e.g. all the yaml describing the pods and other resources in the cluster), and the `meta/query-times.json` file is also very bare.

After all those thoughts; I'd have a few follow up questions for you:
 - Has this been reproducible?
 - Check the cluster to see if all the containers are still around. It seems odd that it was complaining about failing to list pods but since the plugins ran you clearly could _create_ pods and I'm guessing the cleanup routine also was OK so you could _delete_ pods.

Without much else to go on, I'm left wondering if the auth system can ever give false negatives; did some temporary error give rise to a situation where k8s couldn't determine if the acct had access to a resource and so it defaulted to denying the request.

@zubron Any other ideas?

**Comment by johnSchnake** [comment]
Also, a note for this issue:
 - It would have been useful if that error message gave some extra debug information about when that was triggered.
 - If it is possible that a few auth responses can be misleading, then we need to enable the queries to retry a few times which is very doable.

**Comment by johnSchnake** [comment]
Also, FYI, as of Sonobuoy 0.16.1 (I think thats the right version) we default to using the `E2E_USE_GO_RUNNER` if you're using the CLI to do `sonobuoy run`, so you didnt have to specify that manually.

**Comment by zubron** [comment]
I was also just looking at the logs and noticed that the e2e pod log file ends abruptly, and close to the end of the file you can see the following error (beginning line 12851):

```
STEP: Destroying namespace "custom-resource-definition-4778" for this suite.
Dec 10 18:49:24.252: INFO: Error while waiting for namespace to be terminated: Get https://100.64.0.1:443/api/v1/namespaces/custom-resource-definition-4778: dial tcp 100.64.0.1:443: connect: connection refused
Dec 10 18:49:30.888: INFO: Error while waiting for namespace to be terminated: namespaces "custom-resource-definition-4778" is forbidden: User "system:serviceaccount:sonobuoy:sonobuoy-serviceaccount" cannot get resource "namespaces" in API group "" in the namespace "custom-resource-definition-4778"
Dec 10 18:49:36.254: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
Dec 10 18:49:36.335: INFO: namespace custom-resource-definition-4778 deletion completed in 14.151319489s
````

It looks like there was a temporary error in attempting to delete the namespace created as part of the test. It seems like it failed to connect to the API server, encountered an auth error but then retried and succeeded.

**Comment by johnSchnake** [comment]
Good find! That does seem to verify the idea that the auth errors can be transient which I am pretty sure our code does not assume.

Going to consider this ticket scoped to adding that retry logic then. SGTY?

**Comment by dmitry-irtegov** [comment]
Hi @johnSchnake
> slightly confused about the kubeconfig settings; in the issue description you specify kubeconfig when checking the version (sonobuoy version --kubeconfig dvi-5231-ct-1575995653-admin-config.yaml) but do not specify it when running the kubectl auth can-i ... command.

Other commands (including sonobuoy run) were using KUBECONFIG environment variable, which sonobuoy version does not seem to understand.  I'm pretty sure it was the same config, because at the moment I had no other live clusters with sonobuoy. 

> Has this been reproducible?
On our custom installer, yes.  I hit this on a test cluster with logging/monitoring, then I created a bare minimum cluster and hit it again.  Not tried on standard installers like kubeadm though.

May be we had some issue on cluster or infrastructure side, like OOMkilled critical pods.  Need to check this, transient API failures do not look good.

> Check the cluster to see if all the containers are still around. It seems odd that it was complaining about failing to list pods but since the plugins ran you clearly could create pods and I'm guessing the cleanup routine also was OK so you could delete pods.

When I checked the cluster, sonobuoy container was on, but test containers were deleted.  There was a namespace custom-resource-definition-4778 with some secret object.  Later, I had to clean up the cluster and stop it, but I can try to reproduce the condition again,

**Comment by johnSchnake** [comment]
Another 👍 for this; I just got notified of another user hitting a problem in the same way but with a different error text from the API server:
```
{"error":"the server was unable to return a response in the time allotted, but may still be processing the request (get pods)"}
```
