### ISSUE TITLE
Is the "images download" command needed?

### ISSUE THREAD

**Issue by zubron** [vmware-tanzu/sonobuoy#1058]
There is a `download` subcommand under `images`. The purpose of this command is to download the images for the E2E plugin into a tarball. However, this won't work for our recent releases as a number of the images included in the E2E images list are unreachable. They either don't exist or require authentication. These images have been kept in the list to maintain consistency with upstream however Sonobuoy can't do anything with them. They also cause the `download` command to always fail as we can't exclude them.

Given that we have had no feedback from users regarding this, should we remove the `download` command? Or should we update our images list to exclude images that can't be accessed by Sonobuoy?

**Comment by johnSchnake** [comment]
@stevesloka Do you remember the details on the download command from when you implemented it? I assume it was for a flow of downloading them, transferring them physically to another network via a thumb drive or something, then uploading them with docker upload?

I don't recall what our thinking was for the unreachable/auth-required images. I don't really utilize those commands personally and had thought the behavior was that each image would pass/fail on its own and that the whole command wouldn't be aborted.

I think that is a reasonable way to approach it; just log everything appropriately and even change the exit code perhaps if we hit errors. In the end the user can still get the resulting tarball with all the images we could collect.

Thoughts?

**Comment by stevesloka** [comment]
If I remember correctly, the download command used the local user's docker client to download images.  

1. Download images to your local docker client
2. Define a new registry to upload and push them to a private registry

The model around using the local docker client was that it would have the proper credentials to pull/push to any registry 

I'm not sure what images would require auth to pull, they should all be the upstream images and public but agree a log level would be a good start to see what's going on. 

Let me know if I can help further. =)

**Comment by vladimirvivien** [comment]
@wilsonehusin take a 👀

**Comment by wilsonehusin** [comment]
> Given that we have had no feedback from users regarding this, should we remove the download command?

The Marie Kondo in me agrees with this, since I suspect the more popular workflow is to run `pull` then `push`.

Since images are tagged to the repository, I suspect the downloaded images will need manual re-tagging to be pushed to another repository. One way I can think where `download` command can be useful is for the workflow as such:
- `sonobuoy images download`
- `kind load image-archive downloaded-images.tar.gz`
- `sonobuoy run`

I don't know if any other cluster provisioner provide the same `load image-archive` feature as KinD though.

On the other hand, `sonobuoy images push` handles this re-tagging workflow nicely.

@vladimirvivien thoughts?
