### ISSUE TITLE
Alternative Results Format

### ISSUE THREAD

**Issue by kristinafischer** [vmware-tanzu/sonobuoy#1168]
**Describe the solution you'd like**
I would like an alternative to the results tarball. Specifically, I'm looking to expose Sonobuoy results in a way that prometheus can scrape, thereby giving me the ability to monitor and alert on non-conformance.

**Comment by vladimirvivien** [comment]
@kristinafischer Thanks for the issue.  We can track this issue in the future.

**Comment by kristinafischer** [comment]
@vladimirvivien I have begun looking into this and I have some initial design thoughts and questions:

Sonobuoy supports different result formats and the Sonobuoy worker sidecar can obtain a plugin’s result format from the `RESULT_TYPE` parameter. I want to add functionality to the worker subcommand to parse the plugin results and write prometheus metrics to a [prometheus pushgateway](https://github.com/prometheus/pushgateway). The Sonobuoy worker subcommand could then have a flag to enable this pushgateway feature and a configuration option to specify the pushgateway endpoint.

The reason I want to add this functionality to the worker subcommand is because the worker is already running in the k8s cluster and would have access to write to a pushgateway. 

I would start by adding this feature with junit support only. Ideally there would be some standardization of result format across all plugins so that this feature does not have to accommodate all of the existing result format options. There is a related issue [here](https://github.com/vmware-tanzu/sonobuoy/issues/1008). Are there any plans to standardize the result format in the future?

Do you have any concerns with this design?

**Comment by vladimirvivien** [comment]
@kristinafischer 
Thanks for the comprehensive outline of your ideas. I do have a question: what data points would be pushed to Prometheus ? Is it the summary result, each entry as captured in junit, etc?  

Currently, Sonobuoy aggregator can prepare data in junit format (default). What it sounds like you are asking for is another format, maybe the prometheus exposition format, that can be pushed to a gateway by the aggregator.

I think this is an interesting idea cc @wilsonehusin

**Comment by wilsonehusin** [comment]
(I know a bit about Prometheus, though I don't _know_ it the same way that people who run Prometheus in production, so I'd like to hear your thoughts and understand your perspective better!)

I agree this is interesting! I also want to understand more about the usage -- @kristinafischer, you mentioned "the ability to monitor and alert on non-conformance" and I'm wondering _what would one do given such alert_.

Will we be storing enough information to Prometheus? From what I understand, the [Prometheus metric types](https://prometheus.io/docs/concepts/metric_types/) which we can use for JUnit is probably `gauge` where 1 represents failing test, 0 for passing tests (or vice versa). Would an indicator of a failing test have enough meanings without their logs? If so, then I think this is worth pursuing. Otherwise, maybe we can discuss more about what's a realistic goal and useful feature to have.

Happy to chat more about this -- I'm `@wilsonehusin` on Kubernetes Slack if you'd like to setup a call to discuss more.
