### ISSUE TITLE
Make log level configurable

### ISSUE THREAD

**Issue by wilsonehusin** [vmware-tanzu/sonobuoy#1189]
### Description

Sonobuoy currently logs to stderr for `DEBUG` level and above. Ideally we'd like this to be configurable at runtime.

Implementation can either use environment variables (i.e. `LOG_LEVEL=DEBUG`) or global flags (i.e. `--debug` / `--verbose=3`)

### Notes

There are `TODO` marks to downgrade log levels once this feature is achieved (e.g. [`pkg/image/docker/client.go`](https://github.com/vmware-tanzu/sonobuoy/blob/185c859371c7dfa6858906ab6e1f220c51cfaf0b/pkg/image/docker/client.go#L39-L50))

**Comment by vladimirvivien** [comment]
not stale

**Comment by johnSchnake** [comment]
We have

```
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity'
```
and
```
  -d, --debug                            Enable debug output (includes stack traces)
```

I don't usually set them; but do they not work? Sounds like either we don't utilize them or just didnt know they were there when this ticket was made. Can you give a specific example of where you see it not working?

**Comment by johnSchnake** [comment]
So I think the issue is that most of those existing flags are from `klog.InitFlags` and klog is, if I recall, used mainly (only?) on the server side (e.g. in worker/aggregator modes).

The linked comment about info/debug is w.r.t. logrus which is used on the client side.

I'll take a look at this and either make things customizable or squash down the choices so logging is consistent. Its always nice to remove dependencies.
