### ISSUE TITLE
Log line looks suspicious with IP address in square brackets [array/list] - https://[10.0.30.10]:8080/

### ISSUE THREAD

**Issue by spkane** [vmware-tanzu/sonobuoy#1219]
**What steps did you take and what happened:**

I am trying to troubleshoot an issue I am having running sonobuoy in EKS. I noticed this in the logs, and am wondering if the formatting of that log message is to be expected. Square brackets around the IP address seem suspicious.

```
time="2021-03-12T22:50:50Z" level=info msg="Starting to listen on port 8099 for progress updates and will relay them to https://[10.0.30.10]:8080/api/v1/progress/by-node/ip-10-0-56-110.us-west-2.compute.internal/systemd-logs"
```

**What did you expect to happen:**

That this URL look like a valid URL.

**Anything else you would like to add:**
N/A

**Environment:**

- Sonobuoy version: v0.20.0
- Kubernetes version: (use `kubectl version`): v1.19.6-eks-49a6c0
- Kubernetes installer & version: AWS EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Amazon Linux 2
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
>    A host identified by an Internet Protocol literal address, version 6
   [RFC3513] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").  This is the only place where
   square bracket characters are allowed in the URI syntax.  In
   anticipation of future, as-yet-undefined IP literal address formats,
   an implementation may use an optional version flag to indicate such a
   format explicitly rather than rely on heuristic determination.

      IP-literal = "[" ( IPv6address / IPvFuture  ) "]"

      IPvFuture  = "v" 1*HEXDIG "." 1*( unreserved / sub-delims / ":" )

That is an ipv4 address though, so to me, that indicates a malformed IP address. That being said, I assume that it gets processed appropriately by most systems (just a guess).

That string is made via a `url.URL` object and its `.String()` method from the standard library. I'm trying to confirm when/where the brackets are introduced but Go does parse the address just fine with or without the brackets.

If you have a follow-up question, let me know and if I confirm anything new I'll let you know as well. Otherwise, I'll close this as answered within a day or so.

**Comment by johnSchnake** [comment]
Found it: https://github.com/vmware-tanzu/sonobuoy/pull/545

So, as suspected, it was added specifically to support ipv6 but works just fine with ipv4 despite it _technically_ not following the spec (unless I'm reading it wrong).

Hope this helps understand the issue. Good luck with troubleshooting your main issue, let us know if we can help.

**Comment by AlekSi** [comment]
A bit strange that https://golang.org/pkg/net/#JoinHostPort wasn't used
