### ISSUE TITLE
Error for image pull for [sig-cli] test-Kubectl client Kubectl copy within kubectl-1634 namespace

### ISSUE THREAD

**Issue by rajeshsingh624** [vmware-tanzu/sonobuoy#1262]
**What steps did you take and what happened:**
Getting Error: ErrImagePull for tests performed with --focus=[sig-cli] 
Test = [sig-cli] Kubectl client Kubectl copy

The test was performed in airgap environment and all the required images were pre-pulled and pushed to the private registry.

**command used :**
sonobuoy run --plugin e2e --e2e-repo-config custom-image-config --mode=certified-conformance --sonobuoy-image 10.2.10.20:5000/sonobuoy:v0.20.0  --kube-conformance-image 10.2.10.20:5000/conformance:v1.18.6  --e2e-focus="\\[sig-cli\\]"

image repo was provided to sonobuoy via config - custom-image-config
```
[root@bootstrap sonobuoy]# cat custom-image-config
buildImageRegistry: 10.2.10.20:5000
dockerGluster: 10.2.10.20:5000
dockerLibraryRegistry: 10.2.10.20:5000
e2eRegistry: 10.2.10.20:5000
e2eVolumeRegistry: 10.2.10.20:5000
gcRegistry: 10.2.10.20:5000
promoterE2eRegistry: 10.2.10.20:5000
sigStorageRegistry: 10.2.10.20:5000
```

**ERROR**
```
  Warning  Failed          3m14s                  kubelet            Failed to pull image "busybox": rpc error: code = Unknown desc = failed to pull and unpack
 image "docker.io/library/busybox:latest": failed to resolve reference "docker.io/library/busybox:latest": failed to do request: Head https://registry-1.docker
.io/v2/library/busybox/manifests/latest: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:57273->127.0.0.53:53: i/o timeout
```
**What did you expect to happen:**
The image was not mentioned during the sonobuoy image pull, for busybox:latest version.
Also, the test doesn't seem to look for the required image in cursom registry. 

**Environment:**
- Sonobuoy version: v0.20.0
- Kubernetes version: (use `kubectl version`): v1.18.6

**Comment by johnSchnake** [comment]
Thanks for the issue report! We will definitely look into this; we've gotten a similar complaint recently and have other upstream issues with certain tests not respecting those values or properly listing their required images.

**Comment by johnSchnake** [comment]
Hm; so something is off since I see the "latest" tag and I know busy box is in general defined in the test image stuff: https://github.com/kubernetes/kubernetes/blob/v1.18.6/test/utils/image/manifest.go#L211

You can see the test at your k8s version here just uses a hardcoded yaml file, which uses busybox if you check:
/Users/jschnake/go/src/github.com/kubernetes/kubernetes/test/e2e/kubectl/kubectl.go

This was fixed in this commit: https://github.com/kubernetes/kubernetes/commit/aaa90476cbd30e0e71bf6967a947472f79e8b042

So unfortunately you've just hit one of the cases that show the point that upstream tests are a bit messy and multiple folks are working around these issues at the same time.

Thank you for reporting this though and please continue to report issues you have like this, if I hadn't seen it as already fixed upstream I would have done so.
