### ISSUE TITLE
Conformance Test issues - Related to issue "Extend default timeout"?

### ISSUE THREAD

**Issue by fabianKingKong** [vmware-tanzu/sonobuoy#1272]
Once again i run a conformance Test with the following setup:

OS: Opensuse LEAP 1.15 
Runtime: docker
Kubernetes: 1.17.12

I recognized a bunch of Network errors like 
- connection timed out 
- failed to post progress update 
- failed to send progress update to aggregator 
- waiting for webhook configuration to be ready
- Client.Timeout exceeded while awaiting headers
-  ...

Fortunately i could retrieve my results. The results are independent from the Runtime (crio, docker) and the kubernetes Version (
1.17.12, 1.18.16, 1.19.8, 1.20.4). Every permutation result in the same error which can be whitnessed in the following example tar balls:

OS: Opensuse LEAP 1.15 
Runtime: docker
Kubernetes: 1.17.12
[202105201029_sonobuoy_9c16d651-42fc-42c2-a3aa-b3b4e067a55c.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6516340/202105201029_sonobuoy_9c16d651-42fc-42c2-a3aa-b3b4e067a55c.tar.gz)

OS: Opensuse LEAP 1.15 
Runtime: docker
Kubernetes: 1.18.16
[202105201428_sonobuoy_311a2061-cf60-42f1-9447-ac27019322c9.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6520340/202105201428_sonobuoy_311a2061-cf60-42f1-9447-ac27019322c9.tar.gz)

OS: Opensuse LEAP 1.15 
Runtime: docker
Kubernetes: 1.19.18
[202105201755_sonobuoy_408774d0-4204-4553-a959-61c9a7fe0059.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6520346/202105201755_sonobuoy_408774d0-4204-4553-a959-61c9a7fe0059.tar.gz)

OS: Opensuse LEAP 1.15 
Runtime: docker
Kubernetes: 1.20.4
[202105202123_sonobuoy_9c29b6ad-1f89-4ae9-b6e4-7af35a194faa.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6520349/202105202123_sonobuoy_9c29b6ad-1f89-4ae9-b6e4-7af35a194faa.tar.gz)

OS: Opensuse LEAP 1.15 
Runtime: crio
Kubernetes: 1.17.12
[202105210047_sonobuoy_a364ffb7-a872-4f3d-a146-10b6dfadf320.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6520352/202105210047_sonobuoy_a364ffb7-a872-4f3d-a146-10b6dfadf320.tar.gz)

**Comment by johnSchnake** [comment]
So there seems to be an issue between the e2e pod and the aggregator; the aggregator isn't even getting progress updates despite the plugin running:

> time="2021-05-20T14:32:04Z" level=error msg="Failed to send progress update to aggregator: Post \"https://[192.168.129.194]:8080/api/v1/progress/global/e2e\": dial tcp 192.168.129.194:8080: connect: connection timed out"

On the v1.18 one I can see there is the timeout issue legitimately though, so the extended timeout will help (again you can always extend this yourself with the timeout flag as well). This is from the e2e logs themselves.

> "total":277,"completed":192,"skipped":3662,"failed":32,"failures"...

On the 1.20 version I didnt see e2e pods at all and I wonder if it is because they finished and exited/cleaned up in some manner. Typically the plugins should hang around a bit until they're cleaned up but maybe that flow didn't happen because of the connectivity issues to the aggregator?

It is curious why the e2e plugin pod seems to have this connectivity issue but not the systemd-logs plugin. I'll have to look at it a bit more, but maybe the above analysis helps you narrow it down?

**Comment by fabianKingKong** [comment]
Thanks for the response! Where can i find the sonobuoy version where the timeout is extended? Or how can i extend it by myself?

**Comment by johnSchnake** [comment]
You can use the `--timeout` flag to specify the number of seconds it waits. The default is 10800, we doubled it on the master branch.

The flag is the easiest way to change it. If you really dont want a timeout just set it to a high value. Especially if you are monitoring the run (and not automating it where it would eat resources even if it hung) I'd set it to 24h -> `--timeout=86400`

Good luck testing and let us know if you run into any other problems. Happy to help.
