### ISSUE TITLE
Waiting for Results although timeout flag used

### ISSUE THREAD

**Issue by fabianKingKong** [vmware-tanzu/sonobuoy#1279]
Once again i tried a run with the following command:

`sonobuoy run --timeout=86400 --mode=certified-conformance`

The setup was the following:

CentOS 7
Crio
K8s: 1.17.12
[202105250555_sonobuoy_be932bcb-8bc7-48aa-9398-863273720c36.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6543966/202105250555_sonobuoy_be932bcb-8bc7-48aa-9398-863273720c36.tar.gz)

CentOS 7
Crio
K8s: 1.18.16
[202105251027_sonobuoy_43785abb-a0a8-4ef9-ac24-4edf8be658ab.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6543969/202105251027_sonobuoy_43785abb-a0a8-4ef9-ac24-4edf8be658ab.tar.gz)

CentOS 7
Crio
K8s: 1.19.8
[202105252200_sonobuoy_c079d2a1-80f9-4494-88a7-70571c0fcfc4.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6543973/202105252200_sonobuoy_c079d2a1-80f9-4494-88a7-70571c0fcfc4.tar.gz)

CentOS 7
Crio
K8s: 1.19.2
[results040CentOSCrio-1.19.2.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6546208/results040CentOSCrio-1.19.2.tar.gz)

All 4 tests same result: error --> waiting for results.

**FYI: I ran the the conformance Test without the timeout flag with the same setup with docker. All 3 tests passed... But using crio and either with or without the timeout flag, no results...**

**Comment by johnSchnake** [comment]
So 'timeout' is definitely an overloaded word. The `--timeout` option you are specifying is the Sonobuoy timeout. That is how long Sonobuoy will wait for all the plugins (here just the e2e plugin) to report their results.

The timeout you are seeing for individual tests is a timeout coded into the tests themselves.

There is no relationship between those and any correlation between green/red individual tests and that setting are just coincidental.

**Comment by fabianKingKong** [comment]
Okay sorry so i misunderstood the `--timeout` flag. Any further suggestions how i can fix my problem?

**Comment by johnSchnake** [comment]
I don't have any particular expertise in what could slow things down in your situation. For one of the failures I saw it depended on a podlogs/secret timeout and the code for calculating that is based on a label on the nodes. See https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/pod/resource.go#L612-L647

Each test could be different though; could be hardcoded in one test, calculated in another, and totally configurable in the third. Sorry I don't have more information for you but you'll just have to comb through the code.

If you get to a place where you need help passing values to the tests to configure something differently I can definitely help.

**Comment by fabianKingKong** [comment]
Alright, so can i find any Overview about values which i can pass through? Or can you recommend some values which make sense to pass through?

**Comment by johnSchnake** [comment]
Unfortunately there are not good docs for that sort of thing, I would say because of the rate of change, number of developers working, and their priority.

However, you should approach it this way:
 - make a list of the tests you had timeout with crio consistently (that arent timing out in other runs)
 - grep the codebase and read the logic of those tests to see if they are editable in any way or can give clues why it would timeout
 - If you see they are editable with flags and such, check out https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go which is where all the test context/flag logic is

In addition, I would strongly argue for taking some time and combing through the logs/events that you can pull from the cluster. Sonobuoy should have pulled all that stuff down so take a look in the tarball and see if you can find other clues if connections were being rejected, other errors, components failing, etc.
