### ISSUE TITLE
Option to return non-zero exit code for `sonobuoy results` on test failures

### ISSUE THREAD

**Issue by z0rc** [vmware-tanzu/sonobuoy#1305]
**Describe the solution you'd like**
I'm running sonobuoy within Gitlab CI. Currently when running `sonobuoy results` at the end of pipeline it returns zero when it was able to parse results archive. I'm looking for option to return non-zero exit code when `sonobuoy results` successfully parses archive, but there were test failures. This would allow to mark job as failed.

**Anything else you would like to add:**
Workaround would be something like `sonobuoy results ... | grep -q -v "Failed: 0"` which has potential to break, as user facing information isn't strictly stable or deterministic.

**Environment:**

- Sonobuoy version: 0.51.0
- Kubernetes version: (use `kubectl version`): 1.20.4
- Kubernetes installer & version: EKS 1.20
- Cloud provider or hardware configuration: AWS EKS
- OS (e.g. from `/etc/os-release`): Bottlerocket OS

**Comment by johnSchnake** [comment]
It is smart to be cautious when parsing/relying on user facing output.

I would say that in this case my recommendation would be to do something similar but more deterministic. I would just change the mode to `--mode=detailed` or `--mode=dump` so that you see the full/exact of the results. Then you can grep as needed for failures. This has the benefit of relying on the YAML of our results format itself and not just a user facing string. If we change the format we would definitely consider that a breaking change and 1) try and prevent it entirely 2) report it at a minimum 3) work with users to provide  support for existing workflows in some capacity.

ref: https://sonobuoy.io/docs/v0.51.0/results/#manual-results-format

If you're dealing with the e2e tests (which produces junit output) `--mode=detailed` will output the json which you can use jq to search/filter with:

```
sonobuoy results $outfile -p=e2e --mode=detailed
...
{"name":"[sig-storage] In-tree Volumes [Driver: rbd][Feature:Volumes][Serial] [Testpattern: Dynamic PV (ntfs)][sig-windows] subPath should fail if non-existent subpath is outside the volume [Slow][LinuxOnly]","status":"skipped","meta":{"path":"e2e|junit_01.xml|Kubernetes e2e suite"}}
{"name":"[sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: gce-localssd-scsi-fs] [Serial] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] should concurrently access the single read-only volume from pods on the same node","status":"skipped","meta":{"path":"e2e|junit_01.xml|Kubernetes e2e suite"}}
{"name":"[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Pre-provisioned PV (default fs)] subPath should support file as subpath [LinuxOnly]","status":"skipped","meta":{"path":"e2e|junit_01.xml|Kubernetes e2e suite"}}
...
```

Or you can utilize the YAML format Sonobuoy uses for all plugins and yq or grep:
```
sonobuoy results $outfile -p=e2e --mode=dump
...
    - name: '[sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: gce-localssd-scsi-fs]
        [Serial] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow]
        should concurrently access the single read-only volume from pods on the same
        node'
      status: skipped
    - name: '[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern:
        Pre-provisioned PV (default fs)] subPath should support file as subpath [LinuxOnly]'
      status: skipped
...
```

**Comment by z0rc** [comment]
Thanks, I'll check out alternative output modes, checking status field with jq looks promising.
