### ISSUE TITLE
Conformance Test failed - Inexplicable behavior

### ISSUE THREAD

**Issue by fabianKingKong** [vmware-tanzu/sonobuoy#1358]
Hello,
I ran the CNCF conformance test with the following Setup:
` sonobuoy run --timeout=86400 --mode=certified-conformance`

Kubernetes 1.17.17, Crio:
[202107151456_sonobuoy_8b7206ad-2ca8-45f4-9cb9-707d566e3206.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6828144/202107151456_sonobuoy_8b7206ad-2ca8-45f4-9cb9-707d566e3206.tar.gz)

Kubernetes 1.18.19, Crio:
[202107151921_sonobuoy_ff39eb59-d174-4e49-a557-ed6eddbf2aed.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6828147/202107151921_sonobuoy_ff39eb59-d174-4e49-a557-ed6eddbf2aed.tar.gz)

Kubernetes 1.19.11, Crio:
[202107152353_sonobuoy_32f081e5-3da7-4453-ba1a-e6692c779af4.tar.gz](https://github.com/vmware-tanzu/sonobuoy/files/6828150/202107152353_sonobuoy_32f081e5-3da7-4453-ba1a-e6692c779af4.tar.gz)

I tried to understand the results but i do not understand the outcome. I started each test under the same condition and i got different results. The e2e.txt shows me one time 50 fails then 44 fails and in the third test 47 fails.

Can you help me to understand whats going wrong? I dont know but something is completely messed up.

**Comment by johnSchnake** [comment]
I don't really see anything _wrong_ with the results and they seem to me to indicate real issues with the underlying implementations/deployment. Unfortunately the error messages are pretty opaque when it turns out to be things like 'timeout when waiting for the condition'.

Two things to note though:
 - I did notice that there was an error sending update messages at some point which seems to have caused `terminated state (exit code 1)` and so the test results didn't really get reported as expected. I consider this to be a bug and can file a separate ticket upstream for that.
 - I also noticed that the systemd-logs may have gathered some useful clues. If you search the `systemd_logs` files for `level=warning` you may find something relevant. I would scan those lines for clues to which pods/containers failed and see if you can line them up with the tests/namespaces/etc that the failed tests were using. It will be frustrating to track down though.

Unfortunately this does seem like a legitimate error though I'm not an expert on CRIO or these tests specifically so you may need to consult subject matter experts as you continue.

Just keep in mind that the results tarball comes with other useful things for debugging: the systemd_logs as well as other API server data it queries after the run. So you can try and cross reference all the pods/namespaces/errors/timestamps/etc to try and track things down.

How did you create/obtain the clusters in question? Is there a particular tool/launcher you used or are developing, hence the full certified-conformance run?

**Comment by johnSchnake** [comment]
Regarding the failure to post an update -> entering the terminated state: that doesnt seem to be the case upon trying to repro it. I caused the same error but it doesn't impact the exit code.

What I think is the case is that failing tests always causes the exit code 1 issue, but then (in the run I was looking at) progress and results failed to send. So then the aggregator saw no results _and_ the exit 1 on the container and assumed there was a problem.

No underlying bug I think; going to re-check the logs though.

**Comment by johnSchnake** [comment]
Confirmed it just logs errors, doesnt impact exit status: https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/test/e2e/reporters/progress.go#L119

Confirmed the sonobuoy-worker container was unable to submit results:
```
time="2021-07-16T04:02:38Z" level=error msg="error entry for attempt: 1, verb: PUT, time: 2021-07-16 04:02:38.085081289 +0000 UTC m=+14838.043183591, URL: https://[10.85.0.4]:8080/api/v1/results/global/e2e: Put \"https://[10.85.0.4]:8080/api/v1/results/global/e2e\": dial tcp 10.85.0.4:8080: connect: connection refused"
```

Same seems to be true for all the runs/plugins, here is a systemd-logs run:
```
time="2021-07-15T23:16:40Z" level=error msg="error entry for attempt: 1, verb: PUT, time: 2021-07-15 23:16:40.769068353 +0000 UTC m=+4.061050527, URL: https://[10.85.0.4]:8080/api/v1/results/by-node/clustermaster/systemd-logs: Put \"https://[10.85.0.4]:8080/api/v1/results/by-node/clustermaster/systemd-logs\": dial tcp 10.85.0.4:8080: connect: no route to host"
```

There it has a similar error reporting results though the error message is different.

**Comment by johnSchnake** [comment]
The address in that form is fine; I confirmed I have runs that work just fine with the that format `[ip]:port`.

I also found 
```
E0715 23:55:07.926601      18 progress.go:119] Failed to post progress update to http://localhost:8099/progress: Post "http://localhost:8099/progress": dial tcp [::1]:8099: connect: connection refused
```

So you can see that it is using the ipv6 loopback address. But a few lines later I also see:
```
Jul 15 19:28:36.707: INFO: Cluster IP family: ipv4
```

I wonder if something is wrong with the ipv4/6 settings in the cluster?

**Comment by johnSchnake** [comment]
Closed due to inactivity; seemed to cluster issue rather than a sonobuoy issue as well. Feel free to repoen if needed.
