### ISSUE TITLE
"sonobuoy run --mode quick --wait" command is not running as expected. 

### ISSUE THREAD

**Issue by NikhilSharmaWe** [vmware-tanzu/sonobuoy#1442]
![Screenshot (465)](https://user-images.githubusercontent.com/77074571/134849279-2f9a3fa0-48da-4b68-8f97-7381040a4299.png)
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

When I run "sonobuoy run --mode quick --wait" command, in sonobuoy status it shows that it is running one e2e test but it is also running a systemd-logs gatherer which takes much more time to pass.

**What did you expect to happen:**
In documentation it is written that - "Note: Using --mode quick will significantly shorten the runtime of Sonobuoy. It runs just a single test, helping to quickly validate your Sonobuoy and Kubernetes configuration." But here systemd-logs is also running and it shows it can take an hour to complete the [process.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: 
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by NikhilSharmaWe** [comment]
There is some change in the command, we can run 1 e2e tests quickly by adding "--plugin e2e" flag for the purpose.

**Comment by johnSchnake** [comment]
Thanks so much for this issue. How did you set up your k8s cluster? If possible, a tarball from this run would be great; did it ever finish?

At first, I'm not sure if this is really systemd-logs still running or a problem with the status not reporting that its finished.

**Comment by NikhilSharmaWe** [comment]
@johnSchnake I am just starting learning about sonobuoy so can you please explain what do you mean by tarball from this run. And by the way I waited for almost 2 hours but the systemd-logs still showed STATUS : running.

**Comment by johnSchnake** [comment]
No worries. If it still said `running` after 2 hours you couldn't get the tarball anyways.

By tarball I mean the results/logs that you get from running `sonobuoy retrieve` after a run completes. However, if it doesn't ever finish then you can't gather that.

How did you create your cluster? Did you have any other logs to share (output from `sonobuoy logs` or `kubectl logs`)?

**Comment by NikhilSharmaWe** [comment]
![Screenshot (485)](https://user-images.githubusercontent.com/77074571/135564589-9c1e7bd0-8cc0-452b-b753-2f239a62ae0f.png)

**Comment by johnSchnake** [comment]
So the main thing I'm curious about is how you set up the cluster in the first place. E.g. did you make it via AWS? Kind? etc.

I can try and repro locally on kind with those versions but without logs (and knowing if yours was the same type of cluster) I can't be sure what the issue was unless I can repro.

I'll work on it but **if you can get me the info (tarball and type of cluster) then it'll be a big help**.
**Also, if you try again right now does it do the same thing for you?** Not sure if you still have the same type of cluster available.

**Comment by NikhilSharmaWe** [comment]
I am running kubernetes provided by Docker Desktop.

**Comment by johnSchnake** [comment]
Thanks; that was the key to repro this.

I've never personally used k8s for docker desktop an dit seems to cause this problem. It will need some more debugging but I suspect there is some k8s limitation. I couldn't even get logs from those containers:

```
$ kubectl logs sonobuoy-systemd-logs-daemon-set-164cfcebcc1041ee-6tnpr -n sonobuoy -c sonobuoy-worker
Error from server: Get "https://192.168.65.4:10250/containerLogs/sonobuoy/sonobuoy-systemd-logs-daemon-set-164cfcebcc1041ee-6tnpr/sonobuoy-worker": open /run/config/pki/apiserver-kubelet-client.crt: no such file or directory
$ kubectl logs sonobuoy-systemd-logs-daemon-set-164cfcebcc1041ee-6tnpr -n sonobuoy -c systemd-logs
Error from server: Get "https://192.168.65.4:10250/containerLogs/sonobuoy/sonobuoy-systemd-logs-daemon-set-164cfcebcc1041ee-6tnpr/systemd-logs": open /run/config/pki/apiserver-kubelet-client.crt: no such file or directory
```

**Comment by johnSchnake** [comment]
So there are 2 issues really:

I'm not 100% how the different local k8s distros work, but docker desktop does something different than KinD somehow and it undermines a few things I guess.

Even though `kubectl logs` doesnt work, `docker logs` does and you can see whats happening then.

```
$docker logs d0a30ff9b56f
chroot: failed to run command 'journalctl': No such file or directory
Plugin is complete. Sleeping indefinitely to avoid container exit and automatic restarts from Kubernetes
$ docker logs a185abff5afd
time="2021-10-02T19:42:34Z" level=info msg="Waiting for waitfile" waitfile=/tmp/results/done
time="2021-10-02T19:42:34Z" level=info msg="Starting to listen on port 8099 for progress updates and will relay them to https://[10.1.0.10]:8080/api/v1/progress/by-node/docker-desktop/systemd-logs"
```

The systemd-logs image fails since journalctl isn't available on the underlying host; this works on KinD but the way they are virtualizing the cluster node must be fundamentally different.

So this _is_ a bug that systemd-logs plugin doesn't properly report the error. Instead the container fails its business logic but then still sleeps forever without submitting results. This means the container stays alive and isn't restarted continually so the aggregator doesn't see anything suspicious. It just looks like the container is doing work for a long time but it is not.

So 2 action items:
1) make a known issues in the faq/readme about systemd-logs and docker desktop
2) make systemd-logs handle this error mode better

Your mitigation is to just add the flag `--plugin e2e` to only run the e2e plugin instead of the default e2e+systemd-logs.
