### ISSUE TITLE
Sonobuoy v0.55.0 was released with incorrect version

### ISSUE THREAD

**Issue by AlekSi** [vmware-tanzu/sonobuoy#1520]
See [here](https://github.com/vmware-tanzu/sonobuoy/blob/v0.55.0/pkg/buildinfo/version.go#L23). That's not a problem for CLI users, as this variable is set by linker [there](https://github.com/vmware-tanzu/sonobuoy/blob/v0.55.0/.goreleaser.yml#L30), but that's a problem for projects using Sonobuoy as a library, like [Talos OS](https://github.com/talos-systems/talos). That variable is later used [to set the default image](https://github.com/vmware-tanzu/sonobuoy/blob/v0.55.0/pkg/config/config.go#L71). In effect, Sonobuoy 0.55 tries to run 0.54 and fails.

I think bumping a version there should be part of the release checklist.

**Comment by johnSchnake** [comment]
Ah I see. Yea I think it may even be on our checklist but I must have forgotten it. I was confused at first since the CLI shows the proper version but you're right that it gets set by the linker at a different state.

I'll make the bump it now and within a week we'll make a v0.55.1 release with it bumped again. That way you can reference the unreleased version via sha if needed for now, or wait until the next one.

Sorry about the inconvenience.
