### ISSUE TITLE
issues with migrating from 0.51 to 0.56 in an air-gapped environment

### ISSUE THREAD

**Issue by johnqa** [vmware-tanzu/sonobuoy#1605]
**What steps did you take and what happened:**
I have a yaml file describing e2e testing generated with sonobuoy 0.51 in an air-gapped environment. Running tests using this file works perfectly.

I tried to upgrade to 0.56 in many ways and never managed to make it work:
1. If I just change in yaml file sonobuoy version from 0.51 to 0.56, I have unknown results for the execution of e2e plugin and the fix with pointing to a differente results dir is not working;
2. If I generate a new yaml file i have 
`WARN[0000] no pods found with label "sonobuoy-component=aggregator" in namespace sonobuoy 
WARN[0000] retrying with deprecated label "run=sonobuoy-master" 
WARN[0000] no pods found with label "run=sonobuoy-master" in namespace sonobuoy 
WARN[0000] Aggregator pod not found, using default pod name "sonobuoy": no pods found with label "run=sonobuoy-master" in namespace sonobuoy 
ERRO[0000] error attempting to run sonobuoy: could not retrieve sonobuoy pod ` 
and no pod is even started.
3. When I try to reconcile the files generated by 0.56 and the working one for 0.51 I have an issue with image being pulled form `k8s.gcr.io/e2e-test-images/agnhost:2.21` even if I do no changes in my repos list (that works with 0.51).

Is there a known migration process from 0.51 to 0.56 in order to have a properly yaml executable file? 

**Environment:**

- Sonobuoy version: 0.56
- Kubernetes version: (use `kubectl version`): 1.20.8
- Kubernetes installer & version: Rancher 2.5.9
- OS (e.g. from `/etc/os-release`): redhat

**Comment by johnSchnake** [comment]
Sorry that you're having so many problems. Let me try and follow up on these questions/issues:

> If I just change in yaml file sonobuoy version from 0.51 to 0.56, I have unknown results for the execution of e2e plugin and the fix with pointing to a differente results dir is not working;

When you update the version, are you changing both the aggregator version AND the "WorkerImage" field in the config? Are you updating the CLI you're using as well? The CLI version shouldn't really matter, but helps me understand what steps you're exactly taking. "Unknown results" issues can come from different problems though: is the e2e plugin giving the results to the sonobuoy worker correctly? Did the sonobuoy worker give those to the aggregator for processing? Did the CLI try and pull the right file down when doing a `retrieve`? Many of these can be diagnosed if you can give me a tarball obtained after a run (if possible) or logs obtained during/after the run if you cant.

> If I generate a new yaml file i have .... and no pod is even started.

It sounds like the aggregator pod just isn't starting; have you done a `kubectl get pods -n sonobuoy -o yaml` to see what the aggregator pod status is and why? If you are in an airgapped situation you'll need to make sure that you've pulled/tagged the new sonobuoy v0.56.0 image that its looking for. We hope to improve the experience when the aggregator fails to start (see #1578)

> When I try to reconcile the files generated by 0.56 and the working one for 0.51 I have an issue with image being pulled form k8s.gcr.io/e2e-test-images/agnhost:2.21 even if I do no changes in my repos list (that works with 0.51).

Sonobuoy v0.51 and v0.56 both do not hard code the list of images to use. The list of images comes from running the e2e image with a special flag that will just dump the images to us. And you say you "have an issue" but I'm not clear what the issue is. Are the versions of that image different (again, this would come from different cluster versions I would suspect)? Is it not respecting your airgapped registry specification? I would just need more information showing what files you were reconciling/how those were generated.

If you can get me some of the extra information I mention above I'd be happy to help debug your issues.

Thanks for taking the time to report your problem and I hope that I can help resolve them.

**Comment by johnqa** [comment]
Hi,
I forgot to mention something that probably was the most important:  I am running my tests from a Windows workstation with Lens. Also generation of config file was done with sonobuoy on Windows.

Regarding the info you asked for:

> If I just change in yaml file sonobuoy version from 0.51 to 0.56, I have unknown results for the execution of e2e plugin and the fix with pointing to a different results dir is not working;

I am updating both the cli and the image from the config to 0.56. But if I run the yaml file that I have for 0.51 with 0.56 cli it works without any issues.

I cannot attach the tarball but if you need specific info from it I can share. 
Pod Logs with errors for the execution:
```time="2022-02-10T09:57:19Z" level=error msg="Result processing error (500): error handling result e2e/global: couldn't decode result e2e/results/global: couldn't uncompress reader: gzip: invalid header"
time="2022-02-10T09:57:20Z" level=info msg="received request" client_cert="[e2e]" method=PUT plugin_name=e2e url=/api/v1/results/global/e2e
time="2022-02-10T09:57:20Z" level=error msg="Result processing error (500): error handling result e2e/global: couldn't decode result e2e/results/global: couldn't uncompress reader: gzip: invalid header"
time="2022-02-10T09:57:21Z" level=info msg="received request" client_cert="[e2e]" method=PUT plugin_name=e2e url=/api/v1/results/global/e2e
time="2022-02-10T09:57:21Z" level=error msg="Result processing error (500): error handling result e2e/global: couldn't decode result e2e/results/global: couldn't uncompress reader: gzip: invalid header"
time="2022-02-10T09:57:22Z" level=info msg="All plugins have completed, status has been updated"
time="2022-02-10T09:59:19Z" level=info msg="Shutting down aggregation server"
time="2022-02-10T09:59:19Z" level=info msg="Log lines after this point will not appear in the downloaded tarball.
```

> If I generate a new yaml file i have errors when triggering the tests

**This one is solved.**
As I said, I am generating the config file to use for sonobuoy execution on a Windows machine. 
When I did it on a Linux server, the config was good and it worked executed.

After some trials  realised that the difference was in the repository config file, that for windows I was having CRLF end of lines. The files for Linux and Windows are identical except for this.
When generating using the file with CRLF my config files has some strange lines:
```kind: ConfigMap
metadata:
labels:
component: sonobuoy
name: sonobuoy-plugins-cm
namespace: sonobuoy
---
apiVersion: v1
data:
img_repositories.yaml: "∩┐╜∩┐╜b\0u\0i\0l\0d\0I\0m\0a\0g\0e\0R\0e\0g\0i\0s\0t\0r\0y\0:\0
\0r\0e\0p\0o\0s\0i\0t\0o\0r\0y\0.\0d\0e\0v\0e\0l\0o\0p\0m\0e\0n\0t\0.\0i\0n\0t\0:\05\00\00\00\0/\0b\0u\0i\0l\0d\0-\0i\0m\0a\0g\0e\0\r\0\n\0d\0o\0c\0k\0e\0r\0G\0l\0u\0s\0t\0e\0r\0:\0
\0r\0e\0p\0o\0s\0i\0t\0o\0r\0y\0.\0d\0e\0v\0e\0l\0o\0p\0m\0e\0n\0t\0.\0i\0n\0t\0:\05\00\00\00\0/\0g\0l\0u\0s\0t\0e\0r\0\r\0\n\0d\0o\0c\0k\0e\0r\0L\0i\0b\0r\0a\0r\0y\0R\0e\0g\0i\0s\0t\0r\0y\0:\0
\0r\0e\0p\0o\0s\0i\0t\0o\0r\0y\0.\0d\0e\0v\0e\0l\0o\0p\0m\0e\0n\0t\0.\0i\0n\0t\0:\05\00\00\00\0/\0l\0i\0b\0r\0a\0r\0y\0\r\0\n\0e\02\0e\0R\0e\0g\0i\0s\0t\0r\0y\0:\0
\0r\0e\0p\0o\0s\0i\0t\0o\0r\0y\0.\0d\0e\0v\0e\0l\0o\0p\0m\0e\0n\0t\0.\0i\0n\0t\0:\05\00\00\00\0/\0k\0u\0b\0e\0r\0n\0e\0t\0e\0s\0-\0e\02\0e\0-\0t\0e\0s\0t\0-\0i\0m\0a\0g\0e\0s\0\r\0\n\0e\02\0e\0V\0o\0l\0u\0m\0e\0R\0e\0g\0i\0s\0t\0r\0y\0:\0
\0r\0e\0p\0o\0s\0i\0t\0o\0r\0y\0.\0d\0e\0v\0e\0l\0o\0p\0m\0e\0n\0t\0.\0i\0n\0t\0:\05\00\00\00\0/\0k\0u\0b\0e\0r\0n\0e\0t\0e\0s\0-\0e\02\0e\0-\0t\0e\0s\0t\0-\0i\0m\0a\0g\0e\0s\0/\0v\0o\0l\0u\0m\0e\0\r\0\n\0g\0c\0R\0e\0g\0i\0s\0t\0r\0y\0:\0
\0r\0e\0p\0o\0s\0i\0t\0o\0r\0y\0.\0d\0e\0v\0e\0l\0o\0p\0m\0e\0n\0t\0.\0i\0n\0t\0:\05\00\00\00\0\r\0\n\0p\0r\0o\0m\0o\0t\0e\0r\0E\02\0e\0R\0e\0g\0i\0s\0t\0r\0y\0:\0
\0r\0e\0p\0o\0s\0i\0t\0o\0r\0y\0.\0d\0e\0v\0e\0l\0o\0p\0m\0e\0n\0t\0.\0i\0n\0t\0:\05\00\00\00\0/\0e\02\0e\0-\0t\0e\0s\0t\0-\0i\0m\0a\0g\0e\0s\0\r\0\n\0s\0i\0g\0S\0t\0o\0r\0a\0g\0e\0R\0e\0g\0i\0s\0t\0r\0y\0:\0
\0r\0e\0p\0o\0s\0i\0t\0o\0r\0y\0.\0d\0e\0v\0e\0l\0o\0p\0m\0e\0n\0t\0.\0i\0n\0t\0:\05\00\00\00\0/\0s\0i\0g\0-\0s\0t\0o\0r\0a\0g\0e\0\r\0\n\0#\0d\0o\0c\0k\0e\0r\0L\0i\0b\0r\0a\0r\0y\0R\0e\0g\0i\0s\0t\0r\0y\0:\0
\0r\0e\0p\0o\0s\0i\0t\0o\0r\0y\0.\0d\0e\0v\0e\0l\0o\0p\0m\0e\0n\0t\0.\0i\0n\0t\0:\05\00\00\00\0\r\0\n\0"```

Best regads,
Ioan

**Comment by johnSchnake** [comment]
Great, I'm sorry I took so long to follow up but I'm glad you figured out the issue.

Cheers
