### ISSUE TITLE
Allow different result types in the e2e plugin

### ISSUE THREAD

**Issue by Laevos** [vmware-tanzu/sonobuoy#1770]
**Describe the solution you'd like**
Currently the `e2e` plugin is hardcoded to only present results in `junit` format. For our testing automation, we'd prefer to have plugins all output the same result types, and in general would like to be able to specify the results type of this plugin. Especially useful for us would be to enable presenting results in the same format as plugins which use the `manual` format and the [plugin-helper](https://github.com/vmware-tanzu/sonobuoy-plugins/tree/main/plugin-helper), but having the full suite of result output types would be ideal.

**Comment by johnSchnake** [comment]
Yes you can get the same format as those plugins that report using the `manual` results format. This is because that `manual` format is what Sonobuoy considers its canonical format and other things like junit and gojson get translated into it.

You can see this in the tarball of results when looking at the plugin results; you'll see a file named `sonobuoy_results.yaml` which has that data.

You can grab that data manually from the tarball or use `sonobuoy results --mode=dump` which prints the yaml file.

I'll close this but if this doesn't answer your question sufficiently please let me know and reopen.
