### ISSUE TITLE
Customizable Aggregator Server Containers.

### ISSUE THREAD

**Issue by chuckha** [vmware-tanzu/sonobuoy#411]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

I would really like to be able to customize this list of containers (as well as custom volumes) https://github.com/heptio/sonobuoy/blob/master/pkg/templates/manifest.go#L146 through the Sonobuoy interface.

**Comment by timothysc** [comment]
Yeah we need to think about the interface around gen a bit more.

**Comment by chuckha** [comment]
I wonder if it would make sense to convert the template to a big ol' go struct. 

Arguments for the conversion include ability to add containers `sonobuouy.Containers = append( . . . )` without messing about with template syntax/yaml. We would also get type safety of objects and we wouldn't have to worry about syntax.

Downsides include probably a fairly large and deeply nested hard to read struct(s).

I could write up a SEP if there is general interest to see what this would look like.

**Comment by timothysc** [comment]
This one may or may not be in scope, bumping down priority for this milestone.

**Comment by stevesloka** [comment]
Hey @chuckha, could you help us explain what needs to happen a bit?

**Comment by chuckha** [comment]
the updated link should be https://github.com/heptio/sonobuoy/blob/aee97214eb903972f1841d4af123755614ed5792/pkg/templates/manifest.go#L187

The idea behind this was that I want to use sonobuoy to be able to generate yaml similar to how scanner works. The custom volumes part would allow the pods to communicate through the sentinel DONEFILE interface we have. 

The use case is for anyone that wants to customize what happens with sonobuoy data. For example, sonobuoy could be scripted with this feature to upload the tarball to some cloud bucket storage (s3).

**Comment by johnSchnake** [comment]
Also similar to #39

**Comment by johnSchnake** [comment]
Need to put a design doc together for this. I really like the idea of being able to do _something_ with the results rather than just sitting on them but I'm not 100% the only/best approach is a donefile/sidecars with the aggregator.

Pros for that approach: it is consistent with how the plugins currently work so it is familiar.

Cons:  Seems like for each bit of functionality it would be a custom image because it would hinge on waiting for the donefile, then acting. This seems to indicate that we would probably be the owners/caretakers of all those images, correct? They would each be small though so maybe not a big deal.

**Comment by johnSchnake** [comment]
Based on lack of feedback from users on this (and its age) I'm questioning how important this is. It is a blocker to no one since they can edit the yaml directly if they desire.
