### ISSUE TITLE
`pkg` and encapsulation

### ISSUE THREAD

**Issue by chuckha** [vmware-tanzu/sonobuoy#460]
**Describe the solution you'd like**
Sonobuoy CLI commands rely on things like `errlog` and other pieces found in the `pkg` package. I don't think these are things that should be exported to a third-party consumer (i'm considering our CLI to be a consumer). In a real world case, we should put anything we don't want exported outside of `github.com/heptio/sonobuoy` in the [special `internal` package](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit).

**Anything else you would like to add:**

**Environment:**

- Sonobuoy version: 
- Kubernetes version: (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by johnSchnake** [comment]
Looking at moving towards go modules this seems to become even more important since there are much stronger compatibility promises made: s://github.com/golang/go/wiki/Modules#semantic-import-versioning

It seems to only apply for packages intended for public consumption so that would be the ensure `pkg` package. So we'd move towards having a `pkg/v1` package that has to remain backwards compatible for all time until we move to `pkg/v2`.

Since the rest of Sonobuoy isnt meant for public consumption I dont think it applies, but I'm still trying to grok the changes implied with go modules so correct me if I'm wrong.

**Comment by johnSchnake** [comment]
Closing this for now; doing some grooming on the issue list in general and closing things if either:
 - they weren't been reported by the community
 - don't have a genuine need to get done

The reason for this is that we tended to use the issue list as a backlog of very minor or wish-list type items which we wish to clear out for now.
