### ISSUE TITLE
RFE: Non-namespace destructive cleanup/delete

### ISSUE THREAD

**Issue by fabioy** [vmware-tanzu/sonobuoy#502]
**Describe the solution you'd like**

Currently, the "Delete" code path (https://github.com/heptio/sonobuoy/blob/master/pkg/client/delete.go) works by deleting all namespaces created by Sonobuoy. It'd be nice if there was a way to clean itself up in a less destructive fashion, for easier integration with tooling and/or CI/CD pipelines.

**Environment:**

- Sonobuoy version: 0.11.4
- Kubernetes version: (use `kubectl version`): 1.9
- Kubernetes installer & version: GKE
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`):

**Comment by johnSchnake** [comment]
@fabioy Can you be more specific about the use case you're talking about? 

What would you _not_ want deleted? It isn't as if the namespace is shared with other tests, since the creation routines fail if the namespace already exists so I'm not sure I understand how it would integrate better in CI if we could leave the namespace around.

**Comment by fabioy** [comment]
Hi, John,

The use case is that I wish there could be a way to have Sonobuoy clean itself up after a test run and revert to a "clean" state w/o having to tear down the namespace in which it was installed. There seems to be oddball file and state left behind, so running multiple sets of tests w/o deleting the Sonobuoy namespace in between them causes unexpected failures (e.g. tests not starting, etc).

As to why not tear the namespace down, it's mostly because I install a side-car pod that reads and post-process test results. Not having to reinstall/configure for each test run would be nice.

**Comment by stevesloka** [comment]
I think moving to a CRD pattern for Sonobuoy would better enable this functionality. This way we could tie runs to each instance of a CRD, but makes Sonobuoy less "one-shot".

**Comment by johnSchnake** [comment]
#701 will assist with this as well; the idea would be that the sonobuoy CLI would be able to just ping the pod running `sonobuoy master` and tell it to accomplish a task like this.

#634 is similar, for anyone curious.

**Comment by johnSchnake** [comment]
Per a security audit #752 we can't do something like exposing an API very easily in a secure way. If we want to accomplish this and other operations while the pod is already deployed, we'll need a new avenue.

**Comment by johnSchnake** [comment]
We now added the owner references to the sonobuoy pods/plugins (#845) so this seems very doable if we just want to add something like `--keep-namespace` to the CLI.

Would that solve your use case @fabioy? I'm still slightly confused because of some of the language in the request, it sounds like you would also like the `sonobuoy` pod to not be deleted (you said you had a "side car pod" doing postprocessing.

**Comment by vladimirvivien** [comment]
@wilsonehusin this is an important one to revisit and possibly reprioritize.
