### ISSUE TITLE
`Status` start time

### ISSUE THREAD

**Issue by stevesloka** [vmware-tanzu/sonobuoy#587]
**Describe the solution you'd like**
It would be neat to see the start time of plugins when looking at `sonobuoy status`. For example, when E2E are running, they may take a while, but when did they start?

```
$ sonobuoy status                                                                                                            
PLUGIN		STATUS		COUNT
e2e		running		1
systemd_logs	complete	1

```

**Comment by johnSchnake** [comment]
I could see that being useful since I do like a `status` that, by itself, has all the needed information to make judgements on it.

However, if we add start time that by itself isnt useful since you'd also need to know the time that was printed.

Currently the annotation looks like 
```
"sonobuoy.hept.io/status": "{\"plugins\":[{\"plugin\":\"e2e\",\"node\":\"\",\"status\":\"complete\"},{\"plugin\":\"systemd_logs\",\"node\":\"kind-control-plane\",\"status\":\"complete\"}],\"status\":\"complete\"}"
```

Would you want to add `current_time` and `start_time` to the top level object? Not sure you really need to record the per-plugin times since those (at least as of now) all start at the same time. If we do staged plugins at some point that could be different though (in which case maybe it makes sense to still add it to the top level object as well as each individual plugin).

Once we decide on the json change to the hep.io/status object the `sonobuoy status` UI change can follow.

**Comment by spiffcs** [comment]
@johnSchnake I can pick this up tonight if you want.

If you still think adding `current_time` and `start_time` to the top level object is valid I'll follow that spec and follow with the UI change. 

Has anything like `staged plugins` gone into the code at this time?

**Comment by johnSchnake** [comment]
@spiffcs That'd be great!

We've made a series of changes lately that would make a tarball easier to digest and this can be another good one.

We've not added any plugin ordering (e.g. staged plugins) yet so there is no complications from that.

I think that the top level status object and each plugin could use a start_time and and current_time. Even if, in most cases, the current time is duplicated it would still be useful if looking at a snippet of the status for a single plugin or seeing drift between the values may indicate some issue.

**Comment by spiffcs** [comment]
Is there a format you want the timestamp to be in?

I found `creationTimestamp` in the `fakeLogData` file and can make sure to conform to that. 

https://github.com/vmware-tanzu/sonobuoy/blob/e18111dc86e708313a0fdd325ca15de1e4cd361c/pkg/plugin/aggregation/testdata/fakeLogData.txt#L1356

**Comment by spiffcs** [comment]
Leaving the user to do the math seemed a little off. 

I decided to go with a `START TIME` and `DURATION` field as part of the `StatusSummary`

![Screen Shot 2019-10-08 at 11 15 03 PM](https://user-images.githubusercontent.com/32073428/66449039-a71c9780-ea21-11e9-8ef8-e3651a2f99a3.png)

I implemented the front end logic under the `cmd/sonobuoy/appstatus.go` as seen above.

If this design looks good I can go ahead and make sure the fields under the `PluginStatus` and `Status` structs are being populated and parsed correctly so they can be displayed while sonobuoy runs.

**Comment by johnSchnake** [comment]
I think it LGTM. 

I think your use of duration is good and if the users have that, then by default the users don't really need to see the start time (that can just be in the `json` in case they want to do something else with it).

I just don't think this new info necessitates 2 extra columns of info by default; more columns means more likely to wrap or confuse/overwhelm users.

Looking forward to the PR.

(PS I don't care about the gofmt stuff; it looks like the import sections in a number of files weren't properly separating out 3rd party libraries vs our own. Gofmt is sorting them, but we really want them listed separately so it isn't really an improvement or any worse either. If it is simple for you to remove those changes then that'd be my preference but I wouldn't worry about it otherwise)

**Comment by johnSchnake** [comment]
@spiffcs I've added this to the next milestone since it seemed like you were close on it. Tag me or ping me directly when the PR goes up. Thanks again.

**Comment by spiffcs** [comment]
Just got back from vacation and will tackle it tonight!

**Comment by spiffcs** [comment]
I got it mostly working. Thanks for the great feedback. I need to figure out a bug regarding duration sometimes not being set in the status object and will take more of a look at it tomorrow afternoon. I incorporated all the feedback from the comment you made.

**Comment by spiffcs** [comment]
@johnSchnake I've basically finished this, but I had one question. 

Duration is currently not being set on the `e2e` plugin.

I tried tracking it to see if data was being passed into this function:
https://github.com/vmware-tanzu/sonobuoy/blob/f3b4e35e1dc6fd6b8ede2e2a5df20476d5a44fb7/pkg/plugin/aggregation/update.go#L137-L161

When I looked there the loop was always:
```
msg=debug progressUpdates="map[]" results="map[]"
```

Those fields are only populated for the node level plugins.

I'm not sure if the correct behavior is if the e2e plugin should be reported in one of those two values when `Annotate` is called or not.
