### ISSUE TITLE
Sonobuoy:  Command line driver for vendors ?

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/sonobuoy#596]
**Describe the solution you'd like**

@timothysc was thinking about an `oh-my-zsh` bash ‘curl and go’ style test runner for e2e’s, … w/ a little focus flags and stuff, could sonobuoy be a place for that , i.e. 

```
curl run-sonubuoy.sh  | sh
```

And then you might get output like this: 

```
Welcome to Sonubuoy, you can test (1) Conformance (2) Storage (3) Networking (4) .... ? Enter a test suite...  [1].

1

Ok, we're detecting version 1.11 on your kubernetes server, is that the version of kubetest that you want to run ?  If not, enter a kubetest version tag (i.e. 1.9)...  [yes].

yes
``` 
Wondering wether Sonobuoy might be a good home for this, or prefer just a separate repo ?  Either way is fine.

**Comment by johnSchnake** [comment]
Always happy to have other ideas for how the community wants to run things. Since we do have the scanner, CLI, and provide interfaces for custom integrations I don't think adding another method to run them into the Sonobuoy repo itself is the best idea.

I'd suggest another repo and then sharing it in the #sonobuoy Kubernetes channel to raise some visibility and see if it resonates.

**Comment by timothysc** [comment]
I like the subcommands focus on suites.

**Comment by jayunit100** [comment]
Sounds like we’re in agreement on the functionality - just reuse existing cmd line runner makes sense
