### ISSUE TITLE
Rerun command

### ISSUE THREAD

**Issue by stevesloka** [vmware-tanzu/sonobuoy#634]
**Describe the solution you'd like**
Today if I execute a run against a cluster, to run the same thing again I have to delete and start over. Would be neat to maybe say `sonobuoy rerun` and it would run the same job that just happened with the same configuration (i.e. custom plugins, etc).

**Comment by lovejoy** [comment]
kubectl   -n heptio-sonobuoy get pod sonobuoy -o yaml > sonobuoy.yaml
kubectl   -n heptio-sonobuoy delete -f  sonobuoy.yaml
kubectl   -n heptio-sonobuoy create -f  sonobuoy.yaml

**Comment by johnSchnake** [comment]
I just made #701 which listed this as just one potential use case.

Also, fwiw, I exec'd into the Sonobuoy pod running master and manually kicked off another run (e.g. `sonobuoy master`) for some testing purpose and was pleasently surprised at how well things worked.

It seemed to run all the plugins and gather results without conflicts and because the results tarball is timestamped, even though the config.json UUID was the same, the filenames did not conflict.

In addition, when running `sonobuoy retrieve` from my client, it downloaded both files and echo'd them to stdout as expected. So in this way you could script around something like this in a useful way by just iterating over the output from or passing it to xargs.

**Comment by johnSchnake** [comment]
Same as #701; closing since we've made the conscious effort to avoid the server from responding to requests mid-run since that adds a large number of security questions/problems.
