### ISSUE TITLE
RFE: Evaluate hosting images on github vs. gcr.io/heptio assets. 

### ISSUE THREAD

**Issue by timothysc** [vmware-tanzu/sonobuoy#776]
**Describe the solution you'd like**
https://github.com/features/package-registry
Apparently github is going to add a image hosting mechanism which will be super helpful to possibly switch to b/c it enables infra to move off of legacy gcr.io hosting.

**Comment by johnSchnake** [comment]
👍 

Benefits that I can see:
 - It would be nice to have it all in one place for smaller mental footprint
   - one less set of creds
   - one less website to know about
 - packages would be published with history/authentication of an actual user, rather than a bot.
   - we could create another bot account to do this, but maybe it makes more sense to keep the human doing the push on the history

Concerns:
 - Docs state: `To avoid breaking projects that may depend on your packages, GitHub Package Registry does not support package deletion or deleting a version of a package` That seems like a big reduction in capabilities. So if we accidentally push broken image, we have no recourse? Seems like a big problem IMO 🔥 

I'll keep this in mind though as things move forward.

**Comment by johnSchnake** [comment]
Talking with some other devs the inability to delete a package doesn't seem to bother most and presents at least one benefit, even for devs/PMs:
 - simplified choice if you do have a release problem. You simply _have_ to fail forward to the next release and be clear/honest about it instead of potentially sneaking in a quick fix to that package

**Comment by johnSchnake** [comment]
If we are going to host the images in github we may want to consider using github actions for CI too. Will need to consider this holistically. On the docs I also found that there are download statistics available, but I'm not certain what details/granularity.

The github actions for CI are apparently not publicly open until Nov; still beta as of now.

**Comment by johnSchnake** [comment]
Moved to dockerhub to be consistent with other vmware-tanzu projects.
