### ISSUE TITLE
Remove deprecated getPodLogs options

### ISSUE THREAD

**Issue by MengmengZHANG** [vmware-tanzu/sonobuoy#789]
**Describe the solution you'd like**
After introducing new getPodLogs options at #788 , some old options are deprecated (LimitSize & LimitTime). The aim of this task is to remove the deprecated fields and all related logic, e.g. corresponding validation, from v0.16.

https://github.com/heptio/sonobuoy/blob/ee6ecc84a101343434290b029ea3949d6ac575bd/pkg/config/config.go#L171-L172

**Anything else you would like to add:**
Currently the new options and old ones co-exist; if both are provided, the old options will override the existing ones.
```json   
"Limits": {
        "PodLogs": {
            "Previous": false,
            "SinceSeconds": null,
            "SinceTime": "2019-06-28T00:34:00Z",
            "Timestamps": true,
            "TailLines": 100,
            "LimitBytes": 100,
            "LimitSize": "",
            "LimitTime": ""
        }
    }
```

These fields are deprecated because:
- they have different format and name comparing to k8s.io/api/core/v1/PodLogOptions
- they have string type, which requires manually parsing and validating them.

**Comment by johnSchnake** [comment]
For context, this was put in during v0.15.0 https://github.com/vmware-tanzu/sonobuoy/blob/ee8a000c26d87aad84f073fed593651def16f689/pkg/buildinfo/version.go

Doesn't really relate to our "3 minor versions" k8s compatibility. Maybe a good time to establish some deprecation policy for things like this. Since it is a config change it could break users; seems like we should at least announce deprecation and add some warnings or something if they are provided.
