### ISSUE TITLE
How to run performance test? If it has capability to run performance tests.

### ISSUE THREAD

**Issue by chowmean** [vmware-tanzu/sonobuoy#943]
I need to run the performance tests. I didn't find any commands or documentation. When I run sonobuoy test it only ran only conformance tests. 
If it has capability to run performance tests, any documentation or help is appreciated.

**Comment by johnSchnake** [comment]
Could you be more specific about what you mean when you say "performance tests"? Which tests are you referring to?

By default Sonobuoy runs the upstream, Kubernetes e2e plugin which has all the tests in the Kubernetes test binary available to it. It is just a matter of telling Sonobuoy which tests you want to run via the focus/skip values: https://sonobuoy.io/docs/v0.16.1/conformance-testing/

**Comment by chowmean** [comment]
I want to run the performance test which uses this plugin. 
https://github.com/mozhuli/kube-performance

Now I can't find the exact steps to be followed. I am a mere beginner and i think there could be better documentation. I can take this up once I am able to run these tests. @johnSchnake

**Comment by johnSchnake** [comment]
Thanks for the link, let me try and address a number of different points which should answer your question:

1) That plugin is really just running a subset of the K8s E2E tests. To run the `Feature:Performance` tests in the e2e suite, you don't need a custom plugin. You can just run `sonobuoy run --e2e-focus="Feature:Performance"` or `sonobuoy run --plugin-env=e2e.E2E_FOCUS=Feature:Performance`. These tests are apparently in the upstream Kubernetes repo so they're already contained within the `e2e` plugin image.

2) That repo looks pretty out of date (2y since the last update) and it isn't very well documented. I wouldn't use their plugin yaml anyways since it probably hasn't gotten pushed in just as long, meaning that the test binary they're using would be very out of date. In addition, their Dockerfile assumes you already have the e2e.test file which means you'll need to manually build the K8s test binary yourself for your k8s version. In some cases, you _may_ wan to do this, but not just run a certain set of tests. See my latest blog post on how you can tweak the e2e test image: https://sonobuoy.io/custom-e2e-image/

3) Some mention of the flags is here: https://sonobuoy.io/docs/v0.16.1/conformance-testing/ but it is also focused on talking about conformance and not how to really run different sets of test. We actually have a ticket open for cleanup up some docs #919 and this is a great addition to that as I can see it is not very clear.

Feel free to reopen if you are still unsure how to proceed. Again, I think all you want to do is:
```
sonobuoy run --e2e-focus="Feature:Performance" --wait
```

If you want to run a dry run first to see the list of tests that _would be run_ you can change that to this:
```
sonobuoy run --e2e-focus="Feature:Performance" --plugin-env e2e.E2E_DRYRUN=true --wait
```

That will run like a normal test run but you can look at the results and see which tests it chose (e.g. passed)

**Comment by chowmean** [comment]
Thanks a lot. :)
