### ISSUE TITLE
sonobuoy delete --all does not remove PodSecurityPolicy - blocks future runs

### ISSUE THREAD

**Issue by K266** [vmware-tanzu/sonobuoy#979]
**What steps did you take and what happened:**
Run conformance tests with `sonobuoy run`
Clean up with `sonobuoy delete --all`
`e2e-test-privileged-psp` still exists and causes future runs to fail.

**What did you expect to happen:**
All resources relating to the tests are deleted.

**Anything else you would like to add:**
The biggest consequence of this was the fact that followup tests failed during the initial PSP creation step:

```
STEP: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in pods-4827
namespace="sonobuoy" pod="sonobuoy-e2e-job-70f4935f50944806" container="sonobuoy-worker"
time="2019-10-29T09:05:09Z" level=info msg="Waiting for waitfile" waitfile=/tmp/results/done
time="2019-10-29T09:05:09Z" level=info msg="Starting to listen on port 8099 for progress updates and will relay them to https://[10.244.2.70]:8080/api/v1/progress/global/e2e"
namespace="sonobuoy" pod="sonobuoy-e2e-job-70f4935f50944806" container="e2e"
Oct 29 09:05:16.765: INFO: Unexpected error occurred: timed out waiting for the condition
[AfterEach] [k8s.io] Pods
  /workspace/anago-v1.15.5-beta.0.35+20c265fef0741d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:151
STEP: Destroying namespace "pods-4827" for this suite.
Oct 29 09:05:22.802: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
Oct 29 09:05:22.983: INFO: namespace pods-4827 deletion completed in 6.216766729s

• Failure in Spec Setup (BeforeEach) [11.408 seconds]
[k8s.io] Pods
/workspace/anago-v1.15.5-beta.0.35+20c265fef0741d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:692
  should be submitted and removed [NodeConformance] [Conformance] [BeforeEach]
  /workspace/anago-v1.15.5-beta.0.35+20c265fef0741d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:697

  Unexpected error:
      <*errors.errorString | 0xc0002c48b0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred

  /workspace/anago-v1.15.5-beta.0.35+20c265fef0741d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/psp_util.go:152
```

After manually deleting the PSP, the tests complete successfully when re-run.

**Environment:**

- Sonobuoy version: v0.15.4
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: DigitalOcean 1.15.5-do.0
- Cloud provider or hardware configuration: DigitalOcean
- OS (e.g. from `/etc/os-release`): Debian do-kube-1.15.5-do.0

**Comment by johnSchnake** [comment]
My strong suspicion is that the namespace was just stuck in a terminating state which is just an issue with k8s namespace deletion in general that may occur.

Do you have a tarball from one of the subsequent test runs to confirm this?

**Comment by K266** [comment]
I confirmed each time that the namespace had been deleted after `sonobuoy delete --all`, the PSP invariably sticks around regardless.
I can provide a tarball from one of the failed runs if needed, but is a complete tarball safe to upload w.r.t. any sensitive/identifying data?

**Comment by johnSchnake** [comment]
Yes it should be safe:
 - by default we don't gather Secrets
 - by default we just gather logs of pods in the sonobuoy namespace
 - all the resource data (e.g. json) shouldn't have anything secure in it

If there is some snippet you're unsure about feel free to redact it and re-tar it before sending.

**Comment by johnSchnake** [comment]
You can also DM me on slack (jschnake) to limit exposure if you are concerned specifically about posting it here.

**Comment by johnSchnake** [comment]
So @zubron pointed out that I was misreading this the entire time. I now see the issue wasn't with the namespace and even I have the psp still existing in my cluster.

However, this normally doesnt cause a problem and the k8s code just allows the psp to already exist w/o error.

The issue you ran into is, unfortunately, just another difficult-to-explain-and-nothing-to-fix kind of timeout when the cluster tried to bind the psp to the namespace.

I do think the framework should clean up that psp but it really is of relatively low consequence since it deliberately codes in, and accepts, the case when the psp already exists.

See the relevant section of code here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/psp.go#L104-L156

**Comment by matoszz** [comment]
Was having `sonobuoy delete --all` ever fixed such that the e2e-test-privileged-psp gets cleaned up? I'm running 1.18 and still see the PSP's residing after deleting, and it also blocks subsequent executions from sonobuoy if the policy exists on the cluster.

**Comment by zubron** [comment]
There have been no changes to Sonobuoy regarding this.

My understanding is that the e2e test framework should be able to handle the existence of this PSP after looking at this function: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/psp.go#L133-L186
If it is failing because the PSP already exists then it seems like an issue with the framework or flaky behaviour in the test suite. 

An issue has been created to address the framework not cleaning this up: https://github.com/kubernetes/kubernetes/issues/92601
